/**
 * Project Manager - Scripts para listar y eliminar proyectos del VPS
 */

/**
 * Genera un script bash que lista todos los proyectos en /root/proyectos/
 * Cada proyecto se imprime en una línea con formato:
 * PROJECT_LINE|name|type|phpVersion|domain|size|containersRunning|containersTotal
 */
export function generateListProjectsScript(): string {
    // Use single quotes for the heredoc-style approach to avoid TS template interpolation issues
    return [
        '#!/bin/bash',
        '',
        'PROJECTS_DIR="/root/proyectos"',
        '',
        'if [ ! -d "$PROJECTS_DIR" ]; then',
        '    echo "PROJECT_LIST_EMPTY"',
        '    exit 0',
        'fi',
        '',
        'echo "PROJECT_LIST_START"',
        '',
        'for dir in "$PROJECTS_DIR"/*/; do',
        '    [ ! -d "$dir" ] && continue',
        '    PNAME=$(basename "$dir")',
        '    ',
        '    PTYPE="unknown"',
        '    PPHP=""',
        '    PDOMAIN=""',
        '    CRUNNING=0',
        '    CTOTAL=0',
        '    ',
        '    if [ -f "$dir/docker-compose.yml" ]; then',
        '        CC=$(cat "$dir/docker-compose.yml" 2>/dev/null)',
        '        ',
        '        if echo "$CC" | grep -qi "n8nio/n8n"; then PTYPE="docker-app-n8n"',
        '        elif echo "$CC" | grep -qi "odoo"; then PTYPE="docker-app-odoo"',
        '        elif echo "$CC" | grep -qi "evolution-api"; then PTYPE="docker-app-evolution"',
        '        elif echo "$CC" | grep -qi "uptime-kuma"; then PTYPE="docker-app-uptime-kuma"',
        '        elif echo "$CC" | grep -qi "portainer"; then PTYPE="docker-app-portainer"',
        '        elif echo "$CC" | grep -qi "php:7.3"; then PTYPE="php"; PPHP="7.3"',
        '        elif echo "$CC" | grep -qi "php:8"; then',
        '            if echo "$CC" | grep -qi "artisan\\|laravel\\|composer"; then PTYPE="laravel"; else PTYPE="php"; fi',
        '            PPHP="8.3"',
        '        fi',
        '        ',
        '        # Try to extract domain from traefik Host rule',
        '        PDOMAIN=$(echo "$CC" | sed -n \'s/.*Host(\\\\\\?`\\([^`\\\\]*\\).*/\\1/p\' 2>/dev/null | head -1)',
        '        if [ -z "$PDOMAIN" ]; then',
        '            PDOMAIN=$(echo "$CC" | sed -n \'s/.*rule=Host(`\\([^`]*\\).*/\\1/p\' 2>/dev/null | head -1)',
        '        fi',
        '        [ -z "$PDOMAIN" ] && PDOMAIN=""',
        '        ',
        '        cd "$dir" 2>/dev/null',
        '        CTOTAL=$(docker compose ps -q 2>/dev/null | wc -l)',
        '        CRUNNING=$(docker compose ps --filter "status=running" -q 2>/dev/null | wc -l)',
        '    fi',
        '    ',
        '    PSIZE=$(du -sh "$dir" 2>/dev/null | awk \'{print $1}\')',
        '    [ -z "$PSIZE" ] && PSIZE="0"',
        '    ',
        '    echo "PROJECT_LINE|$PNAME|$PTYPE|$PPHP|$PDOMAIN|$PSIZE|$CRUNNING|$CTOTAL"',
        'done',
        '',
        'echo "PROJECT_LIST_END"',
    ].join('\n');
}

/**
 * Genera un script bash para reiniciar los contenedores de un proyecto
 * y limpiar caché (artisan optimize para Laravel)
 */
export function generateRestartProjectScript(projectName: string, projectType: string): string {
    const isLaravel = projectType === 'laravel';

    const lines = [
        '#!/bin/bash',
        '',
        'GREEN=\'\\033[0;32m\'',
        'RED=\'\\033[0;31m\'',
        'YELLOW=\'\\033[1;33m\'',
        'CYAN=\'\\033[0;36m\'',
        'NC=\'\\033[0m\'',
        '',
        `PROJECT_NAME="${projectName}"`,
        'PROJECT_DIR="/root/proyectos/$PROJECT_NAME"',
        '',
        'echo -e "${CYAN}"',
        'echo "============================================"',
        'echo "  🔄 Reiniciando Proyecto: $PROJECT_NAME"',
        'echo "============================================"',
        'echo -e "${NC}"',
        '',
        'if [ ! -d "$PROJECT_DIR" ]; then',
        '    echo -e "${RED}❌ Error: El proyecto \'$PROJECT_NAME\' no existe${NC}"',
        '    exit 1',
        'fi',
        '',
        'cd "$PROJECT_DIR"',
        '',
        'echo -e "${YELLOW}[1/3] 🐳 Reiniciando contenedores...${NC}"',
        'docker compose restart 2>/dev/null || docker-compose restart 2>/dev/null || true',
        'sleep 3',
        'echo -e "${GREEN}✓ Contenedores reiniciados${NC}"',
    ];

    if (isLaravel) {
        lines.push(
            '',
            'echo ""',
            'echo -e "${YELLOW}[2/3] 🧹 Limpiando caché Laravel...${NC}"',
            // Detect PHP container name
            `PHP_CONTAINER="${projectName}_php"`,
            'if docker ps --format "{{.Names}}" | grep -q "$PHP_CONTAINER"; then',
            '    docker exec "$PHP_CONTAINER" php artisan optimize:clear 2>/dev/null || true',
            '    docker exec "$PHP_CONTAINER" php artisan optimize 2>/dev/null || true',
            '    docker exec "$PHP_CONTAINER" php artisan config:cache 2>/dev/null || true',
            '    docker exec "$PHP_CONTAINER" php artisan route:cache 2>/dev/null || true',
            '    docker exec "$PHP_CONTAINER" php artisan view:cache 2>/dev/null || true',
            '    echo -e "${GREEN}✓ Caché Laravel limpiado y optimizado${NC}"',
            'else',
            '    echo -e "${YELLOW}⚠️  No se encontró contenedor PHP: $PHP_CONTAINER${NC}"',
            'fi',
        );
    } else {
        lines.push(
            '',
            'echo -e "${YELLOW}[2/3] 🧹 Limpiando caché PHP...${NC}"',
            `PHP_CONTAINER="${projectName}_php"`,
            'if docker ps --format "{{.Names}}" | grep -q "$PHP_CONTAINER"; then',
            '    docker exec "$PHP_CONTAINER" find /tmp -name "sess_*" -mtime +1 -delete 2>/dev/null || true',
            '    echo -e "${GREEN}✓ Sesiones antiguas limpiadas${NC}"',
            'else',
            '    echo -e "${GREEN}✓ Sin contenedor PHP para limpiar${NC}"',
            'fi',
        );
    }

    lines.push(
        '',
        'echo ""',
        'echo -e "${YELLOW}[3/3] 🔐 Ajustando permisos...${NC}"',
        'if [ -d "$PROJECT_DIR/public" ]; then',
        '    chown -R www-data:www-data "$PROJECT_DIR/public" 2>/dev/null || true',
        '    echo -e "${GREEN}✓ Permisos ajustados${NC}"',
        'elif [ -d "$PROJECT_DIR/src" ]; then',
        '    chown -R www-data:www-data "$PROJECT_DIR/src" 2>/dev/null || true',
        '    echo -e "${GREEN}✓ Permisos ajustados${NC}"',
        'else',
        '    echo -e "${GREEN}✓ Sin ajuste de permisos necesario${NC}"',
        'fi',
        '',
        'echo ""',
        'echo -e "${GREEN}"',
        'echo "============================================"',
        'echo "  ✅ Proyecto \'$PROJECT_NAME\' reiniciado"',
        'echo "============================================"',
        'echo -e "${NC}"',
    );

    return lines.join('\n');
}

/**
 * Genera un script bash para eliminar completamente un proyecto
 */
export function generateDeleteProjectScript(projectName: string): string {
    // Only the projectName comes from JS, rest is pure bash
    return [
        '#!/bin/bash',
        'set -e',
        '',
        'GREEN=\'\\033[0;32m\'',
        'RED=\'\\033[0;31m\'',
        'YELLOW=\'\\033[1;33m\'',
        'CYAN=\'\\033[0;36m\'',
        'NC=\'\\033[0m\'',
        '',
        `PROJECT_NAME="${projectName}"`,
        'PROJECT_DIR="/root/proyectos/$PROJECT_NAME"',
        '',
        'echo -e "${CYAN}"',
        'echo "============================================"',
        'echo "  🗑️  Eliminando Proyecto: $PROJECT_NAME"',
        'echo "============================================"',
        'echo -e "${NC}"',
        '',
        'if [ ! -d "$PROJECT_DIR" ]; then',
        '    echo -e "${RED}❌ Error: El proyecto \'$PROJECT_NAME\' no existe en $PROJECT_DIR${NC}"',
        '    exit 1',
        'fi',
        '',
        'echo ""',
        'echo -e "${YELLOW}[1/5] 🐳 Deteniendo contenedores Docker...${NC}"',
        'cd "$PROJECT_DIR" 2>/dev/null || true',
        'if [ -f "docker-compose.yml" ]; then',
        '    docker compose down -v --remove-orphans 2>/dev/null || true',
        '    echo -e "${GREEN}✓ docker compose down completado${NC}"',
        'else',
        '    echo -e "${YELLOW}⚠️  No se encontró docker-compose.yml${NC}"',
        'fi',
        '',
        'echo ""',
        'echo -e "${YELLOW}[2/5] 🗑️  Eliminando contenedores residuales...${NC}"',
        'for c in $(docker ps -a --filter "name=${PROJECT_NAME}" --format "{{.Names}}" 2>/dev/null); do',
        '    docker rm -f "$c" 2>/dev/null || true',
        '    echo -e "${GREEN}  ✓ Contenedor eliminado: $c${NC}"',
        'done',
        '',
        'echo ""',
        'echo -e "${YELLOW}[3/5] 💾 Eliminando volúmenes...${NC}"',
        'for v in $(docker volume ls --filter "name=${PROJECT_NAME}" --format "{{.Name}}" 2>/dev/null); do',
        '    docker volume rm "$v" 2>/dev/null || true',
        '    echo -e "${GREEN}  ✓ Volumen eliminado: $v${NC}"',
        'done',
        '',
        'echo ""',
        'echo -e "${YELLOW}[4/5] 🌐 Eliminando redes...${NC}"',
        'for n in $(docker network ls --filter "name=${PROJECT_NAME}" --format "{{.Name}}" 2>/dev/null); do',
        '    docker network rm "$n" 2>/dev/null || true',
        '    echo -e "${GREEN}  ✓ Red eliminada: $n${NC}"',
        'done',
        '',
        'echo ""',
        'echo -e "${YELLOW}[5/5] 📁 Eliminando archivos del proyecto...${NC}"',
        'rm -rf "$PROJECT_DIR"',
        'echo -e "${GREEN}✓ Carpeta eliminada: $PROJECT_DIR${NC}"',
        '',
        'echo ""',
        'echo -e "${GREEN}"',
        'echo "============================================"',
        'echo "  ✅ Proyecto \'$PROJECT_NAME\' eliminado"',
        'echo "============================================"',
        'echo -e "${NC}"',
    ].join('\n');
}

/**
 * Genera un script bash para exportar (respaldar y comprimir) un proyecto
 */
export function generateExportProjectScript(projectName: string, projectType: string): string {
    return [
        '#!/bin/bash',
        'set -e',
        'export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/snap/bin:$PATH"',
        '[ -f /etc/profile ] && . /etc/profile > /dev/null 2>&1 || true',
        '[ -f ~/.bashrc ] && . ~/.bashrc > /dev/null 2>&1 || true',
        'export PROJECT_NAME="' + projectName + '"',
        'export EXPORT_DIR="/tmp/exports"',
        'export PROJECT_DIR="/root/proyectos/$PROJECT_NAME"',
        'mkdir -p $EXPORT_DIR',
        'cd $PROJECT_DIR',
        '',
        '# Dump database before stopping containers',
        'echo "Exportando base de datos (si aplica)..."',
        'DB_CONTAINER=$(docker compose ps -q postgres 2>/dev/null || docker compose ps -q mariadb 2>/dev/null || docker compose ps -q mysql 2>/dev/null || docker compose ps -q db 2>/dev/null || docker compose ps -q database 2>/dev/null || docker ps -q --filter "name=${PROJECT_NAME}_db" 2>/dev/null || true)',
        '',
        'if [ ! -z "$DB_CONTAINER" ]; then',
        '    # Check if container is running',
        '    DB_RUNNING=$(docker inspect -f "{{.State.Running}}" "$DB_CONTAINER" 2>/dev/null || echo "false")',
        '    if [ "$DB_RUNNING" = "true" ]; then',
        '        # Determine DB type and dump',
        '        if docker exec "$DB_CONTAINER" env 2>/dev/null | grep -q "POSTGRES_DB"; then',
        '            DB_USER=$(docker exec "$DB_CONTAINER" env | grep "POSTGRES_USER=" | cut -d= -f2 | tr -d \'\\r\' || echo "postgres")',
        '            DB_NAME=$(docker exec "$DB_CONTAINER" env | grep "POSTGRES_DB=" | cut -d= -f2 | tr -d \'\\r\' || echo "postgres")',
        '            echo "Dumping PostgreSQL: $DB_NAME..."',
        '            docker exec "$DB_CONTAINER" pg_dump -U "$DB_USER" -d "$DB_NAME" > "$PROJECT_DIR/database_dump.sql" 2>/dev/null || true',
        '        else',
        '            DB_PASS=$(docker exec "$DB_CONTAINER" env | grep -E "MYSQL_ROOT_PASSWORD=|MARIADB_ROOT_PASSWORD=" | cut -d= -f2 | tr -d \'\\r\' || true)',
        '            DB_NAME=$(docker exec "$DB_CONTAINER" env | grep -E "MYSQL_DATABASE=|MARIADB_DATABASE=" | cut -d= -f2 | tr -d \'\\r\' || true)',
        '            echo "Dumping MySQL/MariaDB: $DB_NAME..."',
        '            if [ ! -z "$DB_PASS" ] && [ ! -z "$DB_NAME" ]; then',
        '                docker exec "$DB_CONTAINER" mysqldump -u root -p"$DB_PASS" "$DB_NAME" > "$PROJECT_DIR/database_dump.sql" 2>/dev/null || true',
        '            else',
        '                docker exec "$DB_CONTAINER" mysqldump -u root "$DB_NAME" > "$PROJECT_DIR/database_dump.sql" 2>/dev/null || true',
        '            fi',
        '        fi',
        '        ',
        '        if [ -f "$PROJECT_DIR/database_dump.sql" ] && [ -s "$PROJECT_DIR/database_dump.sql" ]; then',
        '            echo "✓ Base de datos exportada correctamente"',
        '        else',
        '            echo "⚠️ No se pudo exportar la base de datos o está vacía"',
        '            rm -f "$PROJECT_DIR/database_dump.sql"',
        '        fi',
        '    else',
        '        echo "⚠️ Contenedor de BD no está corriendo, omitiendo dump"',
        '    fi',
        'else',
        '    echo "✓ No se detectó contenedor de base de datos"',
        'fi',
        '',
        'echo "Deteniendo contenedores..."',
        'docker compose down',
        'echo "Comprimiendo proyecto..."',
        'tar -czf $EXPORT_DIR/$PROJECT_NAME.tar.gz .',
        '',
        '# Clean up dump file after compression',
        'rm -f "$PROJECT_DIR/database_dump.sql"',
        '',
        'echo "Reiniciando contenedores..."',
        'docker compose up -d',
        'echo "EXPORT_SUCCESS|$EXPORT_DIR/$PROJECT_NAME.tar.gz"',
    ].join('\n');
}

/**
 * Genera un script bash para importar (extraer y configurar) un proyecto
 */
export function generateImportProjectScript(projectName: string, projectType: string, newDomain: string | null): string {
    const isLaravel = projectType === 'laravel';
    
    // Si es un proyecto web y viene con dominio nuevo, debemos inyectarlo.
    const hasNewDomain = newDomain && newDomain.trim().length > 0;

    const lines = [
        '#!/bin/bash',
        'set -e',
        'export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/snap/bin:$PATH"',
        '# Source profile to ensure docker is in PATH for non-interactive SSH sessions',
        '[ -f /etc/profile ] && . /etc/profile > /dev/null 2>&1 || true',
        '[ -f ~/.bashrc ] && . ~/.bashrc > /dev/null 2>&1 || true',
        '',
        'GREEN=\'\\033[0;32m\'',
        'RED=\'\\033[0;31m\'',
        'YELLOW=\'\\033[1;33m\'',
        'CYAN=\'\\033[0;36m\'',
        'NC=\'\\033[0m\'',
        '',
        `PROJECT_NAME="${projectName}"`,
        `NEW_DOMAIN="${newDomain || ''}"`,
        'PROJECTS_DIR="/root/proyectos"',
        'PROJECT_DIR="${PROJECTS_DIR}/${PROJECT_NAME}"',
        'TAR_FILE="/tmp/imports/${PROJECT_NAME}.tar.gz"',
        'SQL_FILE="${PROJECT_DIR}/database_dump.sql"',
        '',
        'echo -e "${CYAN}============================================${NC}"',
        'echo -e "${CYAN}  📥 Iniciando Importación: $PROJECT_NAME${NC}"',
        'echo -e "${CYAN}============================================${NC}"',
        '',
        'if [ ! -f "$TAR_FILE" ]; then',
        '    echo -e "${RED}❌ Error: El archivo comprimido no existe en $TAR_FILE${NC}"',
        '    echo "IMPORT_ERROR|Archivo tarball no encontrado"',
        '    exit 1',
        'fi',
        '',
        'echo -e "${YELLOW}[1/4] 📦 Extrayendo proyecto...${NC}"',
        'mkdir -p "$PROJECTS_DIR"',
        '',
        '# Eliminar proyecto si ya existe para instalar limpio',
        'if [ -d "$PROJECT_DIR" ]; then',
        '    echo "El proyecto ya existe. Limpiando contenedores anteriores primero..."',
        '    cd "$PROJECT_DIR"',
        '    docker compose down -v 2>/dev/null || true',
        '    rm -rf "$PROJECT_DIR"',
        'fi',
        '',
        'mkdir -p "$PROJECT_DIR"',
        'tar -xzvf "$TAR_FILE" -C "$PROJECT_DIR" > /dev/null 2>&1',
        'echo -e "${GREEN}✓ Proyecto extraído en $PROJECT_DIR${NC}"',
        '',
    ];

    if (hasNewDomain) {
        lines.push(
            'echo -e "${YELLOW}[2/4] 🌐 Configurando dominio: $NEW_DOMAIN...${NC}"',
            'cd "$PROJECT_DIR"',
            '',
            '# Check if docker-compose.yml already has Traefik labels',
            'HAS_TRAEFIK_LABELS=$(grep -c "traefik.enable=true" docker-compose.yml 2>/dev/null || echo "0")',
            '',
            'if [ "$HAS_TRAEFIK_LABELS" -gt 0 ]; then',
            '    # Project already has Traefik — just replace the domain',
            '    echo "Proyecto ya tiene configuración Traefik. Reemplazando dominio..."',
            '    OLD_DOMAIN=$(sed -n \'s/.*Host(\\\\\\?`\\([^`\\\\]*\\).*/\\1/p\' docker-compose.yml | head -1 || true)',
            '    if [ -z "$OLD_DOMAIN" ]; then',
            '        OLD_DOMAIN=$(sed -n \'s/.*rule=Host(`\\([^`]*\\).*/\\1/p\' docker-compose.yml | head -1 || true)',
            '    fi',
            '',
            '    if [ ! -z "$OLD_DOMAIN" ]; then',
            '        echo "Dominio antiguo detectado: $OLD_DOMAIN"',
            '        sed -i "s/$OLD_DOMAIN/$NEW_DOMAIN/g" docker-compose.yml',
            '        echo -e "${GREEN}✓ Dominio reemplazado en docker-compose.yml${NC}"',
            '    fi',
            'else',
            '    # Project has NO Traefik labels — inject them',
            '    echo "Proyecto sin Traefik detectado. Inyectando configuración de dominio..."',
            '',
            '    # Detect the internal port from existing ports: mapping',
            '    INTERNAL_PORT=$(sed -n \'s/^[[:space:]]*-[[:space:]]*"\\?\\([0-9]\\+\\):\\([0-9]\\+\\).*$/\\2/p\' docker-compose.yml | head -1)',
            '    [ -z "$INTERNAL_PORT" ] && INTERNAL_PORT="80"',
            '    echo "Puerto interno detectado: $INTERNAL_PORT"',
            '',
            '    # Determine if domain is a subdomain (more than 2 parts)',
            '    DOT_COUNT=$(echo "$NEW_DOMAIN" | tr -cd \'.\' | wc -c)',
            '    BT=\'`\'',
            '    if [ "$DOT_COUNT" -gt 1 ]; then',
            '        HOST_RULE="Host(${BT}${NEW_DOMAIN}${BT})"',
            '    else',
            '        HOST_RULE="Host(${BT}${NEW_DOMAIN}${BT}) || Host(${BT}www.${NEW_DOMAIN}${BT})"',
            '    fi',
            '',
            '    # Find the first service name in docker-compose',
            '    FIRST_SERVICE=$(sed -n \'s/^  \\([a-zA-Z0-9_-]\\+\\):.*$/\\1/p\' docker-compose.yml | head -1)',
            '',
            '    # Remove existing ports: section from the main service (Traefik handles routing)',
            '    # Use python for reliable multi-line YAML editing',
            '    python3 - "$PROJECT_DIR/docker-compose.yml" "$FIRST_SERVICE" "$NEW_DOMAIN" "$HOST_RULE" "$INTERNAL_PORT" <<\'PYEOF\'',
            'import sys, re',
            'compose_file = sys.argv[1]',
            'service_name = sys.argv[2]',
            'new_domain = sys.argv[3]',
            'host_rule = sys.argv[4]',
            'internal_port = sys.argv[5]',
            'project_name = compose_file.split("/")[-2]',
            '',
            'with open(compose_file, "r") as f:',
            '    content = f.read()',
            '',
            '# Find the service block and remove its ports: section',
            'lines = content.split("\\n")',
            'new_lines = []',
            'in_target_service = False',
            'in_ports = False',
            'service_indent = 0',
            'ports_indent = 0',
            'labels_injected = False',
            'networks_injected = False',
            '',
            'for i, line in enumerate(lines):',
            '    stripped = line.lstrip()',
            '    current_indent = len(line) - len(stripped)',
            '',
            '    # Detect if we are inside the target service',
            '    if re.match(r"^  " + re.escape(service_name) + r":\\s*$", line):',
            '        in_target_service = True',
            '        service_indent = current_indent',
            '        new_lines.append(line)',
            '        continue',
            '',
            '    if in_target_service and current_indent <= service_indent and stripped and not stripped.startswith("#"):',
            '        # We left the service block',
            '        # Inject labels and network before leaving if not done yet',
            '        if not labels_injected:',
            '            indent = "      "',
            '            new_lines.append(f"    labels:")',
            '            new_lines.append(f\'{indent}- "traefik.enable=true"\')',
            '            new_lines.append(f\'{indent}- "traefik.docker.network=traefik_network"\')',
            '            new_lines.append(f\'{indent}- "traefik.http.routers.{project_name}-http.rule={host_rule}"\')',
            '            new_lines.append(f\'{indent}- "traefik.http.routers.{project_name}-http.entrypoints=web"\')',
            '            new_lines.append(f\'{indent}- "traefik.http.routers.{project_name}-http.middlewares={project_name}-redirect-https"\')',
            '            new_lines.append(f\'{indent}- "traefik.http.routers.{project_name}-https.rule={host_rule}"\')',
            '            new_lines.append(f\'{indent}- "traefik.http.routers.{project_name}-https.entrypoints=websecure"\')',
            '            new_lines.append(f\'{indent}- "traefik.http.routers.{project_name}-https.tls=true"\')',
            '            new_lines.append(f\'{indent}- "traefik.http.routers.{project_name}-https.tls.certresolver=letsencrypt"\')',
            '            new_lines.append(f\'{indent}- "traefik.http.services.{project_name}-service.loadbalancer.server.port={internal_port}"\')',
            '            new_lines.append(f\'{indent}- "traefik.http.middlewares.{project_name}-redirect-https.redirectscheme.scheme=https"\')',
            '            new_lines.append(f\'{indent}- "traefik.http.middlewares.{project_name}-redirect-https.redirectscheme.permanent=true"\')',
            '            labels_injected = True',
            '        if not networks_injected:',
            '            pass  # We handle network addition separately below',
            '        in_target_service = False',
            '',
            '    # Skip ports: section lines in the target service',
            '    if in_target_service and stripped.startswith("ports:"):',
            '        in_ports = True',
            '        ports_indent = current_indent',
            '        continue',
            '    if in_ports:',
            '        if current_indent > ports_indent or (stripped.startswith("-") and current_indent >= ports_indent):',
            '            continue',
            '        else:',
            '            in_ports = False',
            '',
            '    new_lines.append(line)',
            '',
            '# If labels were not injected (service was last in file), inject before end',
            'if in_target_service and not labels_injected:',
            '    indent = "      "',
            '    new_lines.append(f"    labels:")',
            '    new_lines.append(f\'{indent}- "traefik.enable=true"\')',
            '    new_lines.append(f\'{indent}- "traefik.docker.network=traefik_network"\')',
            '    new_lines.append(f\'{indent}- "traefik.http.routers.{project_name}-http.rule={host_rule}"\')',
            '    new_lines.append(f\'{indent}- "traefik.http.routers.{project_name}-http.entrypoints=web"\')',
            '    new_lines.append(f\'{indent}- "traefik.http.routers.{project_name}-http.middlewares={project_name}-redirect-https"\')',
            '    new_lines.append(f\'{indent}- "traefik.http.routers.{project_name}-https.rule={host_rule}"\')',
            '    new_lines.append(f\'{indent}- "traefik.http.routers.{project_name}-https.entrypoints=websecure"\')',
            '    new_lines.append(f\'{indent}- "traefik.http.routers.{project_name}-https.tls=true"\')',
            '    new_lines.append(f\'{indent}- "traefik.http.routers.{project_name}-https.tls.certresolver=letsencrypt"\')',
            '    new_lines.append(f\'{indent}- "traefik.http.services.{project_name}-service.loadbalancer.server.port={internal_port}"\')',
            '    new_lines.append(f\'{indent}- "traefik.http.middlewares.{project_name}-redirect-https.redirectscheme.scheme=https"\')',
            '    new_lines.append(f\'{indent}- "traefik.http.middlewares.{project_name}-redirect-https.redirectscheme.permanent=true"\')',
            '',
            '# Add traefik_network to the service networks if exists, or add networks section',
            'final_content = "\\n".join(new_lines)',
            '',
            '# Add traefik_network to top-level networks section',
            'if "traefik_network:" not in final_content:',
            '    if "networks:" in final_content:',
            '        # Find the last networks: block (top-level)',
            '        final_lines = final_content.split("\\n")',
            '        result = []',
            '        found_top_networks = False',
            '        for j, fl in enumerate(final_lines):',
            '            result.append(fl)',
            '            # Top-level networks: starts at column 0',
            '            if fl.strip() == "networks:" and not fl.startswith(" "):',
            '                found_top_networks = True',
            '                # Insert traefik_network after next line',
            '            elif found_top_networks and fl.strip() and not fl.startswith(" " * 4):',
            '                found_top_networks = False',
            '            elif found_top_networks and fl.strip().endswith("driver: bridge"):',
            '                result.append("  traefik_network:")',
            '                result.append("    external: true")',
            '                found_top_networks = False',
            '        if found_top_networks:',
            '            result.append("  traefik_network:")',
            '            result.append("    external: true")',
            '        final_content = "\\n".join(result)',
            '    else:',
            '        final_content += "\\n\\nnetworks:\\n  traefik_network:\\n    external: true\\n"',
            '',
            '# Add traefik_network to the service networks list',
            'service_net_pattern = re.compile(r"(  " + re.escape(service_name) + r":.*?)(?=\\n  \\w+:|\\Z)", re.DOTALL)',
            'match = service_net_pattern.search(final_content)',
            'if match:',
            '    service_block = match.group(0)',
            '    if "networks:" in service_block and "traefik_network" not in service_block:',
            '        service_block = service_block.replace("networks:\\n", "networks:\\n      - traefik_network\\n", 1)',
            '        final_content = final_content[:match.start()] + service_block + final_content[match.end():]',
            '    elif "networks:" not in service_block:',
            '        # Add networks section to the service',
            '        insert_pos = service_block.rfind("\\n")',
            '        if insert_pos > 0:',
            '            service_block = service_block[:insert_pos] + "\\n    networks:\\n      - traefik_network" + service_block[insert_pos:]',
            '            final_content = final_content[:match.start()] + service_block + final_content[match.end():]',
            '',
            'with open(compose_file, "w") as f:',
            '    f.write(final_content)',
            'print("docker-compose.yml actualizado con Traefik labels")',
            'PYEOF',
            '',
            '    echo -e "${GREEN}✓ Labels de Traefik inyectadas en docker-compose.yml${NC}"',
            '',
            '    # Ensure Traefik is running on this server',
            '    echo "Verificando que Traefik esté corriendo..."',
            '    if ! docker ps | grep -q "traefik"; then',
            '        echo "Traefik no encontrado. Instalando..."',
            '        TRAEFIK_DIR="/root/traefik"',
            '        mkdir -p "$TRAEFIK_DIR"',
            '        touch "$TRAEFIK_DIR/acme.json"',
            '        chmod 600 "$TRAEFIK_DIR/acme.json"',
            '',
            '        cat > "$TRAEFIK_DIR/traefik.yml" <<\'TCONFIG\'',
            'api:',
            '  dashboard: true',
            '  insecure: false',
            'entryPoints:',
            '  web:',
            '    address: ":80"',
            '    http:',
            '      redirections:',
            '        entryPoint:',
            '          to: websecure',
            '          scheme: https',
            '  websecure:',
            '    address: ":443"',
            'providers:',
            '  docker:',
            '    endpoint: "unix:///var/run/docker.sock"',
            '    exposedByDefault: false',
            '    network: traefik_network',
            'certificatesResolvers:',
            '  letsencrypt:',
            '    acme:',
            '      email: admin@localhost',
            '      storage: /acme.json',
            '      httpChallenge:',
            '        entryPoint: web',
            'TCONFIG',
            '',
            '        cat > "$TRAEFIK_DIR/docker-compose.yml" <<\'TCOMPOSE\'',
            'name: traefik',
            'services:',
            '  traefik:',
            '    image: traefik:v3.4',
            '    container_name: traefik',
            '    restart: unless-stopped',
            '    security_opt:',
            '      - no-new-privileges:true',
            '    ports:',
            '      - "80:80"',
            '      - "443:443"',
            '    volumes:',
            '      - /var/run/docker.sock:/var/run/docker.sock:ro',
            '      - ./traefik.yml:/traefik.yml:ro',
            '      - ./acme.json:/acme.json',
            '    networks:',
            '      - traefik_network',
            '    labels:',
            '      - "traefik.enable=true"',
            'networks:',
            '  traefik_network:',
            '    external: true',
            'TCOMPOSE',
            '',
            '        docker network create traefik_network 2>/dev/null || true',
            '        cd "$TRAEFIK_DIR"',
            '        docker compose up -d',
            '        sleep 3',
            '        cd "$PROJECT_DIR"',
            '        echo -e "${GREEN}✓ Traefik instalado y corriendo${NC}"',
            '    else',
            '        docker network create traefik_network 2>/dev/null || true',
            '        echo -e "${GREEN}✓ Traefik ya está corriendo${NC}"',
            '    fi',
            'fi',
            '',
            '# Update .env if it exists',
            'if [ -f ".env" ]; then',
            '    if grep -q "^APP_URL=" .env; then',
            '        sed -i "s|^APP_URL=.*|APP_URL=https://$NEW_DOMAIN|g" .env',
            '        echo -e "${GREEN}✓ APP_URL actualizado en .env${NC}"',
            '    fi',
            'fi',
            ''
        );
    } else {
        lines.push(
            'echo -e "${YELLOW}[2/4] 🌐 Manteniendo configuraciones y dominio originales...${NC}"',
            'cd "$PROJECT_DIR"'
        );
    }

    lines.push(
        'echo -e "${YELLOW}[3/4] 🐳 Levantando contenedores docker...${NC}"',
        'docker compose up -d',
        'echo -e "${GREEN}✓ Contenedores iniciados${NC}"',
        '',
        'echo -e "${YELLOW}[4/4] 💾 Restaurando base de datos (si aplica)...${NC}"',
        'if [ -f "$SQL_FILE" ]; then',
        '    DB_CONTAINER=$(docker compose ps -q mariadb 2>/dev/null || docker compose ps -q mysql 2>/dev/null || docker compose ps -q db 2>/dev/null || docker compose ps -q database 2>/dev/null || docker compose ps -q postgres 2>/dev/null || docker ps -q --filter "name=${PROJECT_NAME}_db" 2>/dev/null || true)',
        '    ',
        '    if [ ! -z "$DB_CONTAINER" ]; then',
        '        # Determine DB Type',
        '        IS_POSTGRES=false',
        '        if docker exec "$DB_CONTAINER" env 2>/dev/null | grep -q "POSTGRES_DB"; then',
        '            IS_POSTGRES=true',
        '        fi',
        '',
        '        # Wait for database to actually be ready to accept connections',
        '        echo "⏳ Esperando a que la base de datos acepte conexiones..."',
        '        DB_READY=false',
        '        for i in $(seq 1 30); do',
        '            if [ "$IS_POSTGRES" = true ]; then',
        '                if docker exec "$DB_CONTAINER" pg_isready -q 2>/dev/null; then',
        '                    DB_READY=true',
        '                    break',
        '                fi',
        '            else',
        '                if docker exec "$DB_CONTAINER" mysqladmin ping -h localhost --silent 2>/dev/null; then',
        '                    DB_READY=true',
        '                    break',
        '                fi',
        '            fi',
        '            echo "  Intento $i/30 - BD no lista aún, esperando 3s..."',
        '            sleep 3',
        '        done',
        '',
        '        if [ "$DB_READY" = false ]; then',
        '            echo -e "${RED}⚠️ La BD no respondió después de 90s. Intentando restaurar de todos modos...${NC}"',
        '        else',
        '            echo -e "${GREEN}✓ Base de datos lista para recibir conexiones.${NC}"',
        '        fi',
        '',
        '        DB_RESTORE_OK=false',
        '        if [ "$IS_POSTGRES" = true ]; then',
        '             DB_USER=$(docker exec "$DB_CONTAINER" env | grep "POSTGRES_USER=" | cut -d= -f2 | tr -d \'\\r\' || echo "postgres")',
        '             DB_NAME=$(docker exec "$DB_CONTAINER" env | grep "POSTGRES_DB=" | cut -d= -f2 | tr -d \'\\r\' || echo "postgres")',
        '             echo "Restaurando dump en PostgreSQL (DB: $DB_NAME, User: $DB_USER)..."',
        '             if cat "$SQL_FILE" | docker exec -i "$DB_CONTAINER" psql -U "$DB_USER" -d "$DB_NAME" 2>&1; then',
        '                 DB_RESTORE_OK=true',
        '             fi',
        '        else',
        '             DB_PASS=$(docker exec "$DB_CONTAINER" env | grep -E "MYSQL_ROOT_PASSWORD=|MARIADB_ROOT_PASSWORD=" | cut -d= -f2 | tr -d \'\\r\' || true)',
        '             DB_NAME=$(docker exec "$DB_CONTAINER" env | grep -E "MYSQL_DATABASE=|MARIADB_DATABASE=" | cut -d= -f2 | tr -d \'\\r\' || true)',
        '             echo "Restaurando dump en MySQL/MariaDB (DB: $DB_NAME)..."',
        '             if [ ! -z "$DB_PASS" ] && [ ! -z "$DB_NAME" ]; then',
        '                 if cat "$SQL_FILE" | docker exec -i "$DB_CONTAINER" mysql -u root -p"$DB_PASS" "$DB_NAME" 2>&1; then',
        '                     DB_RESTORE_OK=true',
        '                 fi',
        '             else',
        '                 if cat "$SQL_FILE" | docker exec -i "$DB_CONTAINER" mysql -u root "$DB_NAME" 2>&1; then',
        '                     DB_RESTORE_OK=true',
        '                 fi',
        '             fi',
        '        fi',
        '',
        '        if [ "$DB_RESTORE_OK" = true ]; then',
        '            echo -e "${GREEN}✓ Base de datos restaurada correctamente.${NC}"',
        '        else',
        '            echo -e "${RED}⚠️ Primer intento de restauración falló. Reintentando en 10s...${NC}"',
        '            sleep 10',
        '            if [ "$IS_POSTGRES" = true ]; then',
        '                if cat "$SQL_FILE" | docker exec -i "$DB_CONTAINER" psql -U "$DB_USER" -d "$DB_NAME" 2>&1; then',
        '                    echo -e "${GREEN}✓ Base de datos restaurada en segundo intento.${NC}"',
        '                else',
        '                    echo -e "${RED}❌ No se pudo restaurar la base de datos después de reintentar.${NC}"',
        '                fi',
        '            else',
        '                if [ ! -z "$DB_PASS" ] && [ ! -z "$DB_NAME" ]; then',
        '                    if cat "$SQL_FILE" | docker exec -i "$DB_CONTAINER" mysql -u root -p"$DB_PASS" "$DB_NAME" 2>&1; then',
        '                        echo -e "${GREEN}✓ Base de datos restaurada en segundo intento.${NC}"',
        '                    else',
        '                        echo -e "${RED}❌ No se pudo restaurar la base de datos después de reintentar.${NC}"',
        '                    fi',
        '                fi',
        '            fi',
        '        fi',
        '    else',
        '        echo -e "${RED}⚠️ Se encontró dump, pero no un contenedor de DB para restaurar.${NC}"',
        '    fi',
        '    ',
        '    # Limpiar',
        '    rm -f "$SQL_FILE"',
        '',
        '    # Limpiar migraciones de Prisma fallidas (si existen)',
        '    # Apps como Evolution API usan Prisma que rechaza iniciar si hay migraciones fallidas',
        '    if [ ! -z "$DB_CONTAINER" ]; then',
        '        if [ "$IS_POSTGRES" = true ]; then',
        '            PRISMA_TABLE=$(docker exec -i "$DB_CONTAINER" psql -U "$DB_USER" -d "$DB_NAME" -tAc "SELECT tablename FROM pg_tables WHERE tablename=\'_prisma_migrations\';" 2>/dev/null || true)',
        '            if [ ! -z "$PRISMA_TABLE" ]; then',
        '                FAILED_COUNT=$(docker exec -i "$DB_CONTAINER" psql -U "$DB_USER" -d "$DB_NAME" -tAc "SELECT count(*) FROM _prisma_migrations WHERE finished_at IS NULL OR rolled_back_at IS NOT NULL;" 2>/dev/null || echo "0")',
        '                if [ "$FAILED_COUNT" -gt 0 ] 2>/dev/null; then',
        '                    echo -e "${YELLOW}🔧 Limpiando $FAILED_COUNT migraciones Prisma fallidas...${NC}"',
        '                    docker exec -i "$DB_CONTAINER" psql -U "$DB_USER" -d "$DB_NAME" -c "DELETE FROM _prisma_migrations WHERE finished_at IS NULL;" 2>/dev/null || true',
        '                    echo -e "${GREEN}✓ Migraciones Prisma limpiadas.${NC}"',
        '                fi',
        '            fi',
        '        fi',
        '    fi',
        'else',
        '    echo -e "${GREEN}✓ Ningún respaldo SQL detectado. Omitiendo importación DB.${NC}"',
        'fi',
        '',
        'rm -f "$TAR_FILE" || true',
        '',
        '# Verificar que los contenedores estén realmente corriendo',
        'echo ""',
        'echo -e "${CYAN}🔍 Verificando estado de los contenedores...${NC}"',
        'cd "$PROJECT_DIR"',
        'sleep 5',
        '',
        'CRASHED_CONTAINERS=$(docker compose ps --format "{{.Name}} {{.State}}" 2>/dev/null | grep -v "running" || true)',
        'if [ ! -z "$CRASHED_CONTAINERS" ]; then',
        '    echo -e "${RED}⚠️ Algunos contenedores no están corriendo:${NC}"',
        '    echo "$CRASHED_CONTAINERS"',
        '    echo ""',
        '    echo -e "${YELLOW}Reiniciando contenedores...${NC}"',
        '    docker compose down 2>/dev/null || true',
        '    sleep 2',
        '    docker compose up -d',
        '    sleep 8',
        '',
        '    STILL_CRASHED=$(docker compose ps --format "{{.Name}} {{.State}}" 2>/dev/null | grep -v "running" || true)',
        '    if [ ! -z "$STILL_CRASHED" ]; then',
        '        echo -e "${RED}⚠️ Contenedores que siguen sin correr después del reinicio:${NC}"',
        '        echo "$STILL_CRASHED"',
        '        echo -e "${YELLOW}Últimos logs de error:${NC}"',
        '        docker compose logs --tail=20 2>/dev/null || true',
        '    else',
        '        echo -e "${GREEN}✓ Todos los contenedores corriendo tras reinicio.${NC}"',
        '    fi',
        'else',
        '    echo -e "${GREEN}✓ Todos los contenedores están corriendo correctamente.${NC}"',
        'fi',
        '',
        '# Detectar información de acceso',
        'echo ""',
        'echo -e "${CYAN}============================================${NC}"',
        'echo -e "${CYAN}  📋 Información de Acceso${NC}"',
        'echo -e "${CYAN}============================================${NC}"',
        '',
        'SERVER_IP=$(hostname -I 2>/dev/null | awk \'{print $1}\')',
        '[ -z "$SERVER_IP" ] && SERVER_IP=$(curl -s ifconfig.me 2>/dev/null || echo "desconocida")',
        'echo -e "${GREEN}🖥️  IP del servidor: $SERVER_IP${NC}"',
        '',
        '# Detectar dominio desde docker-compose.yml',
        'DETECTED_DOMAIN=""',
        'if [ -f "$PROJECT_DIR/docker-compose.yml" ]; then',
        '    DETECTED_DOMAIN=$(sed -n \'s/.*Host(\\\\\\?`\\([^`\\\\]*\\).*/\\1/p\' "$PROJECT_DIR/docker-compose.yml" 2>/dev/null | head -1)',
        '    [ -z "$DETECTED_DOMAIN" ] && DETECTED_DOMAIN=$(sed -n \'s/.*rule=Host(`\\([^`]*\\).*/\\1/p\' "$PROJECT_DIR/docker-compose.yml" 2>/dev/null | head -1)',
        'fi',
        '',
        'if [ ! -z "$DETECTED_DOMAIN" ]; then',
        '    echo -e "${GREEN}🌐 Dominio: $DETECTED_DOMAIN${NC}"',
        '    echo -e "${YELLOW}   Asegúrate de apuntar el DNS de $DETECTED_DOMAIN a $SERVER_IP${NC}"',
        'fi',
        '',
        '# Detectar puertos expuestos',
        'cd "$PROJECT_DIR"',
        'PORTS=$(docker compose ps --format "{{.Ports}}" 2>/dev/null | sed -n \'s/.*0\\.0\\.0\\.0:\\([0-9]*\\).*/\\1/p\' | sort -u)',
        'if [ ! -z "$PORTS" ]; then',
        '    echo -e "${GREEN}🔌 Puertos expuestos:${NC}"',
        '    for p in $PORTS; do',
        '        echo -e "${GREEN}   → http://$SERVER_IP:$p${NC}"',
        '    done',
        'else',
        '    echo -e "${YELLOW}   (Sin puertos expuestos directamente — puede estar detrás de Traefik)${NC}"',
        'fi',
        '',
        'echo -e "${CYAN}============================================${NC}"',
        'echo ""',
        '',
        'echo -e "${GREEN}============================================"',
        'echo "  ✅ Proyecto \'$PROJECT_NAME\' importado exitosamente"',
        'echo "============================================"',
        'echo -e "${NC}"',
        'echo "IMPORT_SUCCESS|Completado|$SERVER_IP|$DETECTED_DOMAIN|$PORTS"',
    );

    return lines.join('\n');
}


/**
 * Genera un script bash que verifica e instala Docker y Docker Compose
 * en el servidor destino si no están presentes.
 */
export function generatePrepareServerScript(): string {
    return [
        '#!/bin/bash',
        'set -e',
        'export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/snap/bin:$PATH"',
        '[ -f /etc/profile ] && . /etc/profile > /dev/null 2>&1 || true',
        '',
        'GREEN=\'\\033[0;32m\'',
        'YELLOW=\'\\033[1;33m\'',
        'CYAN=\'\\033[0;36m\'',
        'NC=\'\\033[0m\'',
        '',
        'echo -e "${CYAN}🔧 Verificando dependencias del servidor...${NC}"',
        '',
        '# Check Docker',
        'if command -v docker &> /dev/null; then',
        '    echo -e "${GREEN}✓ Docker ya está instalado: $(docker --version)${NC}"',
        'else',
        '    echo -e "${YELLOW}⚠️ Docker no encontrado. Instalando...${NC}"',
        '    apt-get update -qq',
        '    apt-get install -y -qq ca-certificates curl gnupg lsb-release > /dev/null 2>&1',
        '    install -m 0755 -d /etc/apt/keyrings',
        '    curl -fsSL https://download.docker.com/linux/$(. /etc/os-release && echo "$ID")/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg --yes',
        '    chmod a+r /etc/apt/keyrings/docker.gpg',
        '    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/$(. /etc/os-release && echo "$ID") $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null',
        '    apt-get update -qq',
        '    apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin > /dev/null 2>&1',
        '    systemctl start docker',
        '    systemctl enable docker',
        '    echo -e "${GREEN}✓ Docker instalado: $(docker --version)${NC}"',
        'fi',
        '',
        '# Check Docker Compose',
        'if docker compose version &> /dev/null; then',
        '    echo -e "${GREEN}✓ Docker Compose ya está disponible: $(docker compose version)${NC}"',
        'else',
        '    echo -e "${YELLOW}⚠️ Docker Compose plugin no encontrado. Instalando...${NC}"',
        '    apt-get update -qq',
        '    apt-get install -y -qq docker-compose-plugin > /dev/null 2>&1',
        '    echo -e "${GREEN}✓ Docker Compose instalado: $(docker compose version)${NC}"',
        'fi',
        '',
        '# Ensure /root/proyectos exists',
        'mkdir -p /root/proyectos',
        '',
        'echo "PREPARE_SUCCESS|Servidor listo"',
    ].join('\n');
}
